name: Notwendige Dateien für automatisches QuickActions Update anlegen

on:
  push:
    tags:
      - 'clockodo-quick-actions-*'

jobs: 
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Create json
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          VERSION_CUT=$(echo "${VERSION}" | cut -c 34-)
          JSON_STRING=$(printf '{"RegistryKey":"HKUD\\\\Software\\\\co-IT.eu GmbH\\\\Clockodo QuickActions\\\\Version", "Version":"%s"}' "$VERSION_CUT")
          echo $JSON_STRING > advinst_update.json
          readlink -e advinst_update.json
          cat advinst_update.json
      - name: Add json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/advinst_update.json
          tag: ${{ github.ref }}
          overwrite: true
