name: Notwendige Dateien für automatisches QuickActions Update anlegen

on:
  push:
    tags:
      - 'clockodo-quick-actions-*'

jobs: 
  build:
    runs-on: windows-latest
    steps:
      - name: Create json
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          # Remove the first 23 characters (i.e., "clockodo-quick-actions-")
          $versionClean = $env:VERSION.Substring(23)
          
          # Create the JSON string
          $jsonString = '{"RegistryKey":"HKUD\\\\Software\\\\co-IT.eu GmbH\\\\Clockodo QuickActions\\\\Version", "Version":"' + $versionClean + '"}'
          
          # Write the JSON string to a file
          $jsonString | Set-Content -Path advinst_update.json
          
          # Output the file path and contents for verification
          Write-Output (Resolve-Path advinst_update.json)
          Get-Content advinst_update.json

      - name: Add json to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}\advinst_update.json
          tag: ${{ github.ref_name }}
          overwrite: true
